#! /bin/bash

set -euo pipefail

# This script first builds the docker container and then immediately runs it.

if [ ! -e app/.env ]; then
    echo "No file 'app/.env' to source. This is where local environment variables are stored that should not be committed to git."
    echo "That file will be sourced here. See app/example.env for a template."
    echo
    echo
    echo "Aborting!"
    exit 1
fi

source app/.env

sudo docker stop $DOCKER_CONTAINER && sudo docker rm $DOCKER_CONTAINER
