on: [push]
jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker-up
        run: |
          docker-compose --env-file app/.env up -d
          docker ps -a

      - name: test
        run: |
          set -x
          docker ps
          curl http://localhost:4444 || true
          curl http://localhost:3536 || true
          curl http://localhost:80 || true
          #
          # pip install selenium
          # python test/test.py
