on: [push]
jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker-up
        run: |
          docker-compose --env-file app/.env up -d
          docker ps -a
          # give some time for Flask to spin up.
          sleep 20
          docker logs $(docker ps -a | grep effort-log_web | awk '{print $1}') || true

      - name: test
        run: |
          pip install selenium
          python test/test.py
