on: [push]
jobs:
  run-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker-up
        run: |
          docker-compose --env-file app/.env up -d
          docker ps -a

      - name: test
        run: |
          docker ps
          curl http://localhost:4444
          curl http://localhost:3536
          pip install selenium
          python test/test.py
